--- #YAML:1.0
name:                     Template-Plugin-Digest-MD5
version:                  0.04
abstract:                 TT2 interface to the MD5 Algorithm
author:
  - Barbie <barbie@cpan.org>

license:                  artistic_2
distribution_type:        module
installdirs:              site

requires:
  perl:                   5.006
  Template:               2.0
  Template::Plugin:       2.0
  Template::Stash:        2.0
  Digest::MD5:            0
recommends:
  Test::CPAN::Meta:       0
  Test::CPAN::Meta::JSON: 0
  Test::Pod:              1.00
  Test::Pod::Coverage:    0.08
build_requires:
  IO::File:               0
  Test::More:             0.70

provides:
  Template::Plugin::Digest::MD5:
    file:     lib/Template/Plugin/Digest/MD5.pm
    version:  0.04
no_index:
  directory:
    - t
    - examples

resources:
  license:    http://www.perlfoundation.org/artistic_license_2_0
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Template-Plugin-Digest-MD5
  repository: http://github.com/barbie/template-plugin-digest-md5

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0
